services:
  - type: web
    name: go-markdown
    runtime: static
    buildCommand: |
      rm -rf src/content
      git clone https://github.com/danilo1992-sys/obsidian.git src/content
      python3 scripts/fix-content.py
      npm install -g pnpm
      pnpm install --frozen-lockfile
      pnpm build
    staticPublishPath: dist
